# Generated by Django 4.2.1 on 2023-05-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0003_user_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_list',
            field=models.ManyToManyField(null=True, to='dj_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_list',
            field=models.ManyToManyField(null=True, to='dj_app.request'),
        ),
    ]
