# Generated by Django 4.2.1 on 2023-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0004_alter_user_friend_list_alter_user_request_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_list',
            field=models.ManyToManyField(blank=True, to='dj_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_list',
            field=models.ManyToManyField(blank=True, to='dj_app.request'),
        ),
    ]
